spring.application.name=SistemaVagas


spring.datasource.url=jdbc:postgresql://localhost:5432/vagasrh
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=admin
spring.security.user.password=admin